name: Release Drafter Update
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/**'
jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}